# Generated by Django 4.1.2 on 2022-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpay', '0002_totalnumber_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
