# Generated by Django 4.1.2 on 2022-11-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpay', '0004_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='user',
        ),
        migrations.AddField(
            model_name='myorder',
            name='money',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='productname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
