# Generated by Django 4.1.2 on 2022-11-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpay', '0005_remove_myorder_user_myorder_money_myorder_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyOrder',
            new_name='TempMyOrder',
        ),
    ]
