# Generated by Django 4.1.2 on 2022-11-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpay', '0006_rename_myorder_tempmyorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('productname', models.CharField(max_length=200, null=True)),
                ('money', models.CharField(max_length=200, null=True)),
                ('transactionid', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
