# Generated by Django 4.1.2 on 2022-11-09 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpay', '0008_alter_tempmyorder_username_alter_userdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartnumber',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
