# Generated by Django 4.1.2 on 2022-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpay', '0011_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmyorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
